"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-06 10:22:05.395252
"""
from alembic import op
import sqlalchemy as sa
import app.core.db
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('daily_plans',
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('updated_by', sa.String(length=10), nullable=False),
    sa.Column('deleted_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('client_ref', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_plans_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_plans'))
    )
    with op.batch_alter_table('daily_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_plans_client_ref'), ['client_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_plans_plan_date'), ['plan_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_plans_user_id'), ['user_id'], unique=False)

    op.create_table('operation_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('batch_id', sa.String(length=24), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('ts', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=10), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('tool', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=True),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=12), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=False),
    sa.Column('before', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('after', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('result', sa.String(length=10), nullable=False),
    sa.Column('error_code', sa.String(length=40), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('undone_by', sa.String(length=24), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_operation_log_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_log'))
    )
    with op.batch_alter_table('operation_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operation_log_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_log_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_log_ts'), ['ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_log_user_id'), ['user_id'], unique=False)

    op.create_table('projects',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('area', sa.String(length=12), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('updated_by', sa.String(length=10), nullable=False),
    sa.Column('deleted_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('client_ref', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_projects_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_client_ref'), ['client_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_user_id'), ['user_id'], unique=False)

    op.create_table('routines',
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_per_week', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('preferred_days', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('preferred_start', sa.String(length=5), nullable=True),
    sa.Column('preferred_end', sa.String(length=5), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('updated_by', sa.String(length=10), nullable=False),
    sa.Column('deleted_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('client_ref', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_routines_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routines'))
    )
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routines_client_ref'), ['client_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_routines_user_id'), ['user_id'], unique=False)

    op.create_table('study_topics',
    sa.Column('parent_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('resources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('prerequisite_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('updated_by', sa.String(length=10), nullable=False),
    sa.Column('deleted_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('client_ref', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['study_topics.id'], name=op.f('fk_study_topics_parent_id_study_topics')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_study_topics_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_topics'))
    )
    with op.batch_alter_table('study_topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_topics_client_ref'), ['client_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_topics_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_topics_user_id'), ['user_id'], unique=False)

    op.create_table('user_preferences',
    sa.Column('timezone', sa.String(length=60), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('updated_by', sa.String(length=10), nullable=False),
    sa.Column('deleted_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('client_ref', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_preferences_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_preferences'))
    )
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_preferences_client_ref'), ['client_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_preferences_user_id'), ['user_id'], unique=False)

    op.create_table('tasks',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('do_date', sa.Date(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('parent_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('updated_by', sa.String(length=10), nullable=False),
    sa.Column('deleted_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('client_ref', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['tasks.id'], name=op.f('fk_tasks_parent_id_tasks')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_tasks_project_id_projects')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tasks_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_client_ref'), ['client_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_do_date'), ['do_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_user_id'), ['user_id'], unique=False)

    op.create_table('calendar_entries',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('mobility', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('start_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('end_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('skip_reason', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('task_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('study_topic_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('routine_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('project_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('rrule', sa.String(length=300), nullable=True),
    sa.Column('series_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('original_start', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('updated_by', sa.String(length=10), nullable=False),
    sa.Column('deleted_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('client_ref', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_calendar_entries_project_id_projects')),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], name=op.f('fk_calendar_entries_routine_id_routines')),
    sa.ForeignKeyConstraint(['series_id'], ['calendar_entries.id'], name=op.f('fk_calendar_entries_series_id_calendar_entries')),
    sa.ForeignKeyConstraint(['study_topic_id'], ['study_topics.id'], name=op.f('fk_calendar_entries_study_topic_id_study_topics')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_calendar_entries_task_id_tasks')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_calendar_entries_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_entries'))
    )
    with op.batch_alter_table('calendar_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_entries_client_ref'), ['client_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_entries_end_at'), ['end_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_entries_routine_id'), ['routine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_entries_series_id'), ['series_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_entries_start_at'), ['start_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_entries_study_topic_id'), ['study_topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_entries_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_entries_user_id'), ['user_id'], unique=False)

    op.create_table('study_sessions',
    sa.Column('topic_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('entry_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('updated_by', sa.String(length=10), nullable=False),
    sa.Column('deleted_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('client_ref', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['calendar_entries.id'], name=op.f('fk_study_sessions_entry_id_calendar_entries')),
    sa.ForeignKeyConstraint(['topic_id'], ['study_topics.id'], name=op.f('fk_study_sessions_topic_id_study_topics')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_study_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_sessions'))
    )
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_sessions_client_ref'), ['client_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_sessions_session_date'), ['session_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_sessions_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_sessions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_study_sessions_topic_id'))
        batch_op.drop_index(batch_op.f('ix_study_sessions_session_date'))
        batch_op.drop_index(batch_op.f('ix_study_sessions_client_ref'))

    op.drop_table('study_sessions')
    with op.batch_alter_table('calendar_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_entries_task_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_entries_study_topic_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_entries_start_at'))
        batch_op.drop_index(batch_op.f('ix_calendar_entries_series_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_entries_routine_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_entries_end_at'))
        batch_op.drop_index(batch_op.f('ix_calendar_entries_client_ref'))

    op.drop_table('calendar_entries')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_project_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_parent_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_due_date'))
        batch_op.drop_index(batch_op.f('ix_tasks_do_date'))
        batch_op.drop_index(batch_op.f('ix_tasks_client_ref'))

    op.drop_table('tasks')
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_preferences_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_preferences_client_ref'))

    op.drop_table('user_preferences')
    with op.batch_alter_table('study_topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_topics_user_id'))
        batch_op.drop_index(batch_op.f('ix_study_topics_parent_id'))
        batch_op.drop_index(batch_op.f('ix_study_topics_client_ref'))

    op.drop_table('study_topics')
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routines_user_id'))
        batch_op.drop_index(batch_op.f('ix_routines_client_ref'))

    op.drop_table('routines')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_user_id'))
        batch_op.drop_index(batch_op.f('ix_projects_client_ref'))

    op.drop_table('projects')
    with op.batch_alter_table('operation_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operation_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_operation_log_ts'))
        batch_op.drop_index(batch_op.f('ix_operation_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_operation_log_batch_id'))

    op.drop_table('operation_log')
    with op.batch_alter_table('daily_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_plans_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_plans_plan_date'))
        batch_op.drop_index(batch_op.f('ix_daily_plans_client_ref'))

    op.drop_table('daily_plans')
    op.drop_table('users')
    # ### end Alembic commands ###
