"""workouts

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-06 11:06:09.013286
"""
from alembic import op
import sqlalchemy as sa
import app.core.db
from sqlalchemy.dialects import postgresql

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_sessions',
    sa.Column('routine_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('workout_key', sa.String(length=30), nullable=True),
    sa.Column('workout_name', sa.String(length=120), nullable=False),
    sa.Column('entry_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('exercises', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('effort', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('updated_by', sa.String(length=10), nullable=False),
    sa.Column('deleted_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('client_ref', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['calendar_entries.id'], name=op.f('fk_workout_sessions_entry_id_calendar_entries')),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], name=op.f('fk_workout_sessions_routine_id_routines')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workout_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_sessions'))
    )
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_sessions_client_ref'), ['client_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_sessions_entry_id'), ['entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_sessions_routine_id'), ['routine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_sessions_session_date'), ['session_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_sessions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workouts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default=sa.text("'[]'")))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.drop_column('workouts')

    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_workout_sessions_session_date'))
        batch_op.drop_index(batch_op.f('ix_workout_sessions_routine_id'))
        batch_op.drop_index(batch_op.f('ix_workout_sessions_entry_id'))
        batch_op.drop_index(batch_op.f('ix_workout_sessions_client_ref'))

    op.drop_table('workout_sessions')
    # ### end Alembic commands ###
